In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.1.3'

In [4]:
df = pd.read_csv('car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [6]:
df.shape

(9704, 11)

In [8]:
df['fuel_type'].nunique()

2

In [11]:
df.isnull().any().sum()

4

In [12]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [13]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

23.759122836520497

In [ ]:
original_median = df['horsepower'].median()

most_frequent = df['horsepower'].mode()[0]

df['horsepower'] = df['horsepower'].fillna(most_frequent)

new_median = df['horsepower'].median()

print("Original median horsepower:", original_median)
print("Most frequent horsepower value:", most_frequent)
print("New median horsepower after filling missing values:", new_median)

Original median horsepower: 152.0
Most frequent horsepower value: 152.0
New median horsepower after filling missing values: 152.0


In [18]:
X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [19]:
XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [20]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [21]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = XTX_inv @ X.T @ y
result_sum = w.sum()
result_sum

0.5187709081074016